### ISSUE TITLE
I have a problem with this 

### ISSUE THREAD

**Issue by wdrqef** [buiquangmanhhp1999/extract-information-from-identity-card#1]
![image](https://user-images.githubusercontent.com/71751475/102299632-d31c9c80-3f85-11eb-9359-df46eaee3299.png)

**Comment by buiquangmanhhp1999** [comment]
Lỗi này do giá trị của biến img rỗng. Bạn kiểm tra xem có đang truyền giá trị cho biến img  không nhé
