### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by nShieldSolo** [buiquangmanhhp1999/extract-information-from-identity-card#2]
**Hi bro,** 

     Bài viết của bạn rất hữu ít vời mình, cám ơn bạn. Mình thấy bạn đang xài file pretrained của anh Quốc. 
     Thì nó chưa chính xác nên mình hỏi là cần phải train lại không? hay do mình làm sai nên kq chưa chính xác?
       Cám ơn nhiều nhé

**Comment by buiquangmanhhp1999** [comment]
Mình có finetune lại với dữ liệu chứng minh nhân dân nhé bạn ơi. Bạn có thể xài trực tiếp pretrained weight của mình nhé
