### ISSUE TITLE
DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by HuynID** [buiquangmanhhp1999/extract-information-from-identity-card#5]
Em dùng anacoda để install nhưng vẫn không thể chạy được

**Comment by HuynID** [comment]
[
![sc](https://user-images.githubusercontent.com/63187225/115159620-43ffcc80-a0be-11eb-9e01-f0a83adad7e8.PNG)
](url)

**Comment by buiquangmanhhp1999** [comment]
Dùng trên windows có rất nhiều lỗi về môi trường liên quan tới thư viện dùng trong machin learning. Bạn thử chuyển hệ điều hành ubuntu để ổn định nhé
