### ISSUE TITLE
ERROR OpenCV

### ISSUE THREAD

**Issue by ph0810** [buiquangmanhhp1999/extract-information-from-identity-card#7]
![image](https://user-images.githubusercontent.com/61834343/118698218-547ca180-b83a-11eb-817a-10825b14dc36.png) 
khi chạy mình gặp lỗi này. mong mng giúp đỡ

**Comment by ph0810** [comment]
![image](https://user-images.githubusercontent.com/61834343/118699790-2730f300-b83c-11eb-9ff2-55b0366b7359.png)

**Comment by connortran216** [comment]
> ![image](https://user-images.githubusercontent.com/61834343/118699790-2730f300-b83c-11eb-9ff2-55b0366b7359.png)
> hi vọng nhận đc câu trả lời ạ

You can fix it by editing code in line 113 as follow: 

model = VietOCR(len(vocab), config['backbone'], config['cnn'], config['transformer'])#, config['seq_modeling'])

**Comment by buiquangmanhhp1999** [comment]
Mình đã kiểm tra và sửa các lỗi các bạn feedback. Cảm ơn các bạn đã nhận xét cho mình.
