### ISSUE TITLE
Could not open './config_corner_detection/Corner/model.tflite'

### ISSUE THREAD

**Issue by diephieunghia123** [buiquangmanhhp1999/extract-information-from-identity-card#8]
![image](https://user-images.githubusercontent.com/38271721/120881847-3a92db00-c5fe-11eb-9541-ebc5fc305d55.png)
em bị lỗi này ạ và không biết sửa sao. Em xài windows

**Comment by connortran216** [comment]
> ![image](https://user-images.githubusercontent.com/38271721/120881847-3a92db00-c5fe-11eb-9541-ebc5fc305d55.png)
> em bị lỗi này ạ và không biết sửa sao. Em xài windows

You can check the model path again, there is no /Corner/ folder.

**Comment by buiquangmanhhp1999** [comment]
I have already fixed this issue, please dowload source code again. Thanks you
